In [5]:
#Exercicio 1

import numpy as np
import pandas as pd


# Crie um array NumPy com 10 elementos inteiros aleatórios entre 0 e 100
array_random = np.random.randint(0, 101, 10)

# Exiba os valores do array
print("Valores do array:", array_random)

# Exiba o tipo de dado do array
print("Tipo de dado do array:", array_random.dtype)

Valores do array: [  4  66 100  67  60   2   2  87  43  85]
Tipo de dado do array: int32


In [8]:
#Exercicio 2

# Crie uma matriz 5x5 com valores aleatórios entre 0 e 1
matriz = np.random.rand(5, 5)

# Encontre o valor mínimo, máximo e a média da matriz
valor_minimo = matriz.min()
valor_maximo = matriz.max()
media = matriz.mean()

# Exiba os resultados
print("Matriz:")
print(matriz)
print("Valor mínimo:", valor_minimo)
print("Valor máximo:", valor_maximo)
print("Média:", media)

Matriz:
[[0.38905089 0.72755138 0.11609651 0.75195959 0.67412877]
 [0.91294081 0.02126383 0.77088308 0.54669001 0.93767794]
 [0.31605564 0.51787141 0.67677804 0.39807374 0.06312936]
 [0.52535759 0.76976234 0.27553794 0.5727538  0.98480722]
 [0.84128054 0.46149467 0.96861081 0.10372589 0.69091275]]
Valor mínimo: 0.021263834898820444
Valor máximo: 0.9848072246902334
Média: 0.5605757826212217


In [7]:
#Exercicio 3

# Crie um array com 10 elementos aleatórios no intervalo [0, 1]
array_original = np.random.rand(10)

# Crie um novo array com os elementos multiplicados por 10 e convertidos para inteiros
array_novo = (array_original * 10).astype(int)

# Exiba os dois arrays
print("Array Original:", array_original)
print("Array Novo:", array_novo)

Array Original: [0.40801989 0.99241288 0.94363257 0.03713263 0.2579736  0.73323754
 0.26997038 0.75183316 0.99383595 0.00103873]
Array Novo: [4 9 9 0 2 7 2 7 9 0]


In [9]:
#Exercicio 4

# Crie um array de duas dimensões (3x3) com valores aleatórios inteiros entre 0 e 9
array = np.random.randint(0, 10, (3, 3))

# Substitua todos os elementos da segunda linha por -1
array[1, :] = -1

# Exiba o array resultante
print(array)


[[ 8  9  1]
 [-1 -1 -1]
 [ 2  0  6]]


In [14]:
#Exercicio 5

# Criar um dicionário com os dados
data = {
    'Fruta': ['Banana', 'Maçã', 'Pera'],
    'Preço': [7.90, 10.20, 11.80],
    'Quantidade': [12, 3, 4]
}

# Criar o DataFrame
df = pd.DataFrame(data)

# Exibir o DataFrame
print(df)

    Fruta  Preço  Quantidade
0  Banana    7.9          12
1    Maçã   10.2           3
2    Pera   11.8           4
